//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.MNepal.WebReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.nibl.com.np/", ConfigurationName="WebReference.VerifyThisSoap")]
    public interface VerifyThisSoap {
        
        // CODEGEN: Generating message contract since message VerifyTxnRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nibl.com.np/VerifyTxn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WCF.MNepal.WebReference.VerifyTxnResponse VerifyTxn(WCF.MNepal.WebReference.VerifyTxnRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nibl.com.np/VerifyTxn", ReplyAction="*")]
        System.Threading.Tasks.Task<WCF.MNepal.WebReference.VerifyTxnResponse> VerifyTxnAsync(WCF.MNepal.WebReference.VerifyTxnRequest request);
        
        // CODEGEN: Generating message contract since message InquireTxnRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nibl.com.np/InquireTxn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WCF.MNepal.WebReference.InquireTxnResponse InquireTxn(WCF.MNepal.WebReference.InquireTxnRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nibl.com.np/InquireTxn", ReplyAction="*")]
        System.Threading.Tasks.Task<WCF.MNepal.WebReference.InquireTxnResponse> InquireTxnAsync(WCF.MNepal.WebReference.InquireTxnRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nibl.com.np/")]
    public partial class VerifyHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string h1Field;
        
        private string h2Field;
        
        private string h3Field;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string H1 {
            get {
                return this.h1Field;
            }
            set {
                this.h1Field = value;
                this.RaisePropertyChanged("H1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string H2 {
            get {
                return this.h2Field;
            }
            set {
                this.h2Field = value;
                this.RaisePropertyChanged("H2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string H3 {
            get {
                return this.h3Field;
            }
            set {
                this.h3Field = value;
                this.RaisePropertyChanged("H3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerifyTxn", WrapperNamespace="http://www.nibl.com.np/", IsWrapped=true)]
    public partial class VerifyTxnRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.nibl.com.np/")]
        public WCF.MNepal.WebReference.VerifyHeader VerifyHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.nibl.com.np/", Order=0)]
        public object obj1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.nibl.com.np/", Order=1)]
        public object obj2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.nibl.com.np/", Order=2)]
        public object obj3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.nibl.com.np/", Order=3)]
        public object obj4;
        
        public VerifyTxnRequest() {
        }
        
        public VerifyTxnRequest(WCF.MNepal.WebReference.VerifyHeader VerifyHeader, object obj1, object obj2, object obj3, object obj4) {
            this.VerifyHeader = VerifyHeader;
            this.obj1 = obj1;
            this.obj2 = obj2;
            this.obj3 = obj3;
            this.obj4 = obj4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerifyTxnResponse", WrapperNamespace="http://www.nibl.com.np/", IsWrapped=true)]
    public partial class VerifyTxnResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.nibl.com.np/", Order=0)]
        public string VerifyTxnResult;
        
        public VerifyTxnResponse() {
        }
        
        public VerifyTxnResponse(string VerifyTxnResult) {
            this.VerifyTxnResult = VerifyTxnResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InquireTxn", WrapperNamespace="http://www.nibl.com.np/", IsWrapped=true)]
    public partial class InquireTxnRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.nibl.com.np/")]
        public WCF.MNepal.WebReference.VerifyHeader VerifyHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.nibl.com.np/", Order=0)]
        public object obj1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.nibl.com.np/", Order=1)]
        public object obj2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.nibl.com.np/", Order=2)]
        public object obj3;
        
        public InquireTxnRequest() {
        }
        
        public InquireTxnRequest(WCF.MNepal.WebReference.VerifyHeader VerifyHeader, object obj1, object obj2, object obj3) {
            this.VerifyHeader = VerifyHeader;
            this.obj1 = obj1;
            this.obj2 = obj2;
            this.obj3 = obj3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InquireTxnResponse", WrapperNamespace="http://www.nibl.com.np/", IsWrapped=true)]
    public partial class InquireTxnResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.nibl.com.np/", Order=0)]
        public string InquireTxnResult;
        
        public InquireTxnResponse() {
        }
        
        public InquireTxnResponse(string InquireTxnResult) {
            this.InquireTxnResult = InquireTxnResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VerifyThisSoapChannel : WCF.MNepal.WebReference.VerifyThisSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VerifyThisSoapClient : System.ServiceModel.ClientBase<WCF.MNepal.WebReference.VerifyThisSoap>, WCF.MNepal.WebReference.VerifyThisSoap {
        
        public VerifyThisSoapClient() {
        }
        
        public VerifyThisSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VerifyThisSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VerifyThisSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VerifyThisSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCF.MNepal.WebReference.VerifyTxnResponse WCF.MNepal.WebReference.VerifyThisSoap.VerifyTxn(WCF.MNepal.WebReference.VerifyTxnRequest request) {
            return base.Channel.VerifyTxn(request);
        }
        
        public string VerifyTxn(WCF.MNepal.WebReference.VerifyHeader VerifyHeader, object obj1, object obj2, object obj3, object obj4) {
            WCF.MNepal.WebReference.VerifyTxnRequest inValue = new WCF.MNepal.WebReference.VerifyTxnRequest();
            inValue.VerifyHeader = VerifyHeader;
            inValue.obj1 = obj1;
            inValue.obj2 = obj2;
            inValue.obj3 = obj3;
            inValue.obj4 = obj4;
            WCF.MNepal.WebReference.VerifyTxnResponse retVal = ((WCF.MNepal.WebReference.VerifyThisSoap)(this)).VerifyTxn(inValue);
            return retVal.VerifyTxnResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WCF.MNepal.WebReference.VerifyTxnResponse> WCF.MNepal.WebReference.VerifyThisSoap.VerifyTxnAsync(WCF.MNepal.WebReference.VerifyTxnRequest request) {
            return base.Channel.VerifyTxnAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCF.MNepal.WebReference.VerifyTxnResponse> VerifyTxnAsync(WCF.MNepal.WebReference.VerifyHeader VerifyHeader, object obj1, object obj2, object obj3, object obj4) {
            WCF.MNepal.WebReference.VerifyTxnRequest inValue = new WCF.MNepal.WebReference.VerifyTxnRequest();
            inValue.VerifyHeader = VerifyHeader;
            inValue.obj1 = obj1;
            inValue.obj2 = obj2;
            inValue.obj3 = obj3;
            inValue.obj4 = obj4;
            return ((WCF.MNepal.WebReference.VerifyThisSoap)(this)).VerifyTxnAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCF.MNepal.WebReference.InquireTxnResponse WCF.MNepal.WebReference.VerifyThisSoap.InquireTxn(WCF.MNepal.WebReference.InquireTxnRequest request) {
            return base.Channel.InquireTxn(request);
        }
        
        public string InquireTxn(WCF.MNepal.WebReference.VerifyHeader VerifyHeader, object obj1, object obj2, object obj3) {
            WCF.MNepal.WebReference.InquireTxnRequest inValue = new WCF.MNepal.WebReference.InquireTxnRequest();
            inValue.VerifyHeader = VerifyHeader;
            inValue.obj1 = obj1;
            inValue.obj2 = obj2;
            inValue.obj3 = obj3;
            WCF.MNepal.WebReference.InquireTxnResponse retVal = ((WCF.MNepal.WebReference.VerifyThisSoap)(this)).InquireTxn(inValue);
            return retVal.InquireTxnResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WCF.MNepal.WebReference.InquireTxnResponse> WCF.MNepal.WebReference.VerifyThisSoap.InquireTxnAsync(WCF.MNepal.WebReference.InquireTxnRequest request) {
            return base.Channel.InquireTxnAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCF.MNepal.WebReference.InquireTxnResponse> InquireTxnAsync(WCF.MNepal.WebReference.VerifyHeader VerifyHeader, object obj1, object obj2, object obj3) {
            WCF.MNepal.WebReference.InquireTxnRequest inValue = new WCF.MNepal.WebReference.InquireTxnRequest();
            inValue.VerifyHeader = VerifyHeader;
            inValue.obj1 = obj1;
            inValue.obj2 = obj2;
            inValue.obj3 = obj3;
            return ((WCF.MNepal.WebReference.VerifyThisSoap)(this)).InquireTxnAsync(inValue);
        }
    }
}
