//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNepalWeb.NTServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NTServices.NTSoapSoap")]
    public interface NTSoapSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        MNepalWeb.NTServices.HelloWorldResponse HelloWorld(MNepalWeb.NTServices.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<MNepalWeb.NTServices.HelloWorldResponse> HelloWorldAsync(MNepalWeb.NTServices.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name parameters from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/dealerPasswordChange", ReplyAction="*")]
        MNepalWeb.NTServices.dealerPasswordChangeResponse dealerPasswordChange(MNepalWeb.NTServices.dealerPasswordChangeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/dealerPasswordChange", ReplyAction="*")]
        System.Threading.Tasks.Task<MNepalWeb.NTServices.dealerPasswordChangeResponse> dealerPasswordChangeAsync(MNepalWeb.NTServices.dealerPasswordChangeRequest request);
        
        // CODEGEN: Generating message contract since element name mposNumber from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDealerBalance", ReplyAction="*")]
        MNepalWeb.NTServices.getDealerBalanceResponse getDealerBalance(MNepalWeb.NTServices.getDealerBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDealerBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<MNepalWeb.NTServices.getDealerBalanceResponse> getDealerBalanceAsync(MNepalWeb.NTServices.getDealerBalanceRequest request);
        
        // CODEGEN: Generating message contract since element name parameters from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eTopupTransfer", ReplyAction="*")]
        MNepalWeb.NTServices.eTopupTransferResponse eTopupTransfer(MNepalWeb.NTServices.eTopupTransferRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eTopupTransfer", ReplyAction="*")]
        System.Threading.Tasks.Task<MNepalWeb.NTServices.eTopupTransferResponse> eTopupTransferAsync(MNepalWeb.NTServices.eTopupTransferRequest request);
        
        // CODEGEN: Generating message contract since element name mposNumber from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/checkDealer", ReplyAction="*")]
        MNepalWeb.NTServices.checkDealerResponse checkDealer(MNepalWeb.NTServices.checkDealerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/checkDealer", ReplyAction="*")]
        System.Threading.Tasks.Task<MNepalWeb.NTServices.checkDealerResponse> checkDealerAsync(MNepalWeb.NTServices.checkDealerRequest request);
        
        // CODEGEN: Generating message contract since element name mposNumber from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/checkDealerPassword", ReplyAction="*")]
        MNepalWeb.NTServices.checkDealerPasswordResponse checkDealerPassword(MNepalWeb.NTServices.checkDealerPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/checkDealerPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<MNepalWeb.NTServices.checkDealerPasswordResponse> checkDealerPasswordAsync(MNepalWeb.NTServices.checkDealerPasswordRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public MNepalWeb.NTServices.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(MNepalWeb.NTServices.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public MNepalWeb.NTServices.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(MNepalWeb.NTServices.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class dealerPasswordChangeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="dealerPasswordChange", Namespace="http://tempuri.org/", Order=0)]
        public MNepalWeb.NTServices.dealerPasswordChangeRequestBody Body;
        
        public dealerPasswordChangeRequest() {
        }
        
        public dealerPasswordChangeRequest(MNepalWeb.NTServices.dealerPasswordChangeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class dealerPasswordChangeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string parameters;
        
        public dealerPasswordChangeRequestBody() {
        }
        
        public dealerPasswordChangeRequestBody(string parameters) {
            this.parameters = parameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class dealerPasswordChangeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="dealerPasswordChangeResponse", Namespace="http://tempuri.org/", Order=0)]
        public MNepalWeb.NTServices.dealerPasswordChangeResponseBody Body;
        
        public dealerPasswordChangeResponse() {
        }
        
        public dealerPasswordChangeResponse(MNepalWeb.NTServices.dealerPasswordChangeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class dealerPasswordChangeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dealerPasswordChangeResult;
        
        public dealerPasswordChangeResponseBody() {
        }
        
        public dealerPasswordChangeResponseBody(string dealerPasswordChangeResult) {
            this.dealerPasswordChangeResult = dealerPasswordChangeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDealerBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDealerBalance", Namespace="http://tempuri.org/", Order=0)]
        public MNepalWeb.NTServices.getDealerBalanceRequestBody Body;
        
        public getDealerBalanceRequest() {
        }
        
        public getDealerBalanceRequest(MNepalWeb.NTServices.getDealerBalanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getDealerBalanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mposNumber;
        
        public getDealerBalanceRequestBody() {
        }
        
        public getDealerBalanceRequestBody(string mposNumber) {
            this.mposNumber = mposNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDealerBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDealerBalanceResponse", Namespace="http://tempuri.org/", Order=0)]
        public MNepalWeb.NTServices.getDealerBalanceResponseBody Body;
        
        public getDealerBalanceResponse() {
        }
        
        public getDealerBalanceResponse(MNepalWeb.NTServices.getDealerBalanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getDealerBalanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getDealerBalanceResult;
        
        public getDealerBalanceResponseBody() {
        }
        
        public getDealerBalanceResponseBody(string getDealerBalanceResult) {
            this.getDealerBalanceResult = getDealerBalanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eTopupTransferRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="eTopupTransfer", Namespace="http://tempuri.org/", Order=0)]
        public MNepalWeb.NTServices.eTopupTransferRequestBody Body;
        
        public eTopupTransferRequest() {
        }
        
        public eTopupTransferRequest(MNepalWeb.NTServices.eTopupTransferRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class eTopupTransferRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string parameters;
        
        public eTopupTransferRequestBody() {
        }
        
        public eTopupTransferRequestBody(string parameters) {
            this.parameters = parameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eTopupTransferResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="eTopupTransferResponse", Namespace="http://tempuri.org/", Order=0)]
        public MNepalWeb.NTServices.eTopupTransferResponseBody Body;
        
        public eTopupTransferResponse() {
        }
        
        public eTopupTransferResponse(MNepalWeb.NTServices.eTopupTransferResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class eTopupTransferResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string eTopupTransferResult;
        
        public eTopupTransferResponseBody() {
        }
        
        public eTopupTransferResponseBody(string eTopupTransferResult) {
            this.eTopupTransferResult = eTopupTransferResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkDealerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkDealer", Namespace="http://tempuri.org/", Order=0)]
        public MNepalWeb.NTServices.checkDealerRequestBody Body;
        
        public checkDealerRequest() {
        }
        
        public checkDealerRequest(MNepalWeb.NTServices.checkDealerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class checkDealerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mposNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        public checkDealerRequestBody() {
        }
        
        public checkDealerRequestBody(string mposNumber, string Password) {
            this.mposNumber = mposNumber;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkDealerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkDealerResponse", Namespace="http://tempuri.org/", Order=0)]
        public MNepalWeb.NTServices.checkDealerResponseBody Body;
        
        public checkDealerResponse() {
        }
        
        public checkDealerResponse(MNepalWeb.NTServices.checkDealerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class checkDealerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string checkDealerResult;
        
        public checkDealerResponseBody() {
        }
        
        public checkDealerResponseBody(string checkDealerResult) {
            this.checkDealerResult = checkDealerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkDealerPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkDealerPassword", Namespace="http://tempuri.org/", Order=0)]
        public MNepalWeb.NTServices.checkDealerPasswordRequestBody Body;
        
        public checkDealerPasswordRequest() {
        }
        
        public checkDealerPasswordRequest(MNepalWeb.NTServices.checkDealerPasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class checkDealerPasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mposNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        public checkDealerPasswordRequestBody() {
        }
        
        public checkDealerPasswordRequestBody(string mposNumber, string Password) {
            this.mposNumber = mposNumber;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkDealerPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkDealerPasswordResponse", Namespace="http://tempuri.org/", Order=0)]
        public MNepalWeb.NTServices.checkDealerPasswordResponseBody Body;
        
        public checkDealerPasswordResponse() {
        }
        
        public checkDealerPasswordResponse(MNepalWeb.NTServices.checkDealerPasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class checkDealerPasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string checkDealerPasswordResult;
        
        public checkDealerPasswordResponseBody() {
        }
        
        public checkDealerPasswordResponseBody(string checkDealerPasswordResult) {
            this.checkDealerPasswordResult = checkDealerPasswordResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NTSoapSoapChannel : MNepalWeb.NTServices.NTSoapSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NTSoapSoapClient : System.ServiceModel.ClientBase<MNepalWeb.NTServices.NTSoapSoap>, MNepalWeb.NTServices.NTSoapSoap {
        
        public NTSoapSoapClient() {
        }
        
        public NTSoapSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NTSoapSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NTSoapSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NTSoapSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MNepalWeb.NTServices.HelloWorldResponse MNepalWeb.NTServices.NTSoapSoap.HelloWorld(MNepalWeb.NTServices.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            MNepalWeb.NTServices.HelloWorldRequest inValue = new MNepalWeb.NTServices.HelloWorldRequest();
            inValue.Body = new MNepalWeb.NTServices.HelloWorldRequestBody();
            MNepalWeb.NTServices.HelloWorldResponse retVal = ((MNepalWeb.NTServices.NTSoapSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MNepalWeb.NTServices.HelloWorldResponse> MNepalWeb.NTServices.NTSoapSoap.HelloWorldAsync(MNepalWeb.NTServices.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<MNepalWeb.NTServices.HelloWorldResponse> HelloWorldAsync() {
            MNepalWeb.NTServices.HelloWorldRequest inValue = new MNepalWeb.NTServices.HelloWorldRequest();
            inValue.Body = new MNepalWeb.NTServices.HelloWorldRequestBody();
            return ((MNepalWeb.NTServices.NTSoapSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MNepalWeb.NTServices.dealerPasswordChangeResponse MNepalWeb.NTServices.NTSoapSoap.dealerPasswordChange(MNepalWeb.NTServices.dealerPasswordChangeRequest request) {
            return base.Channel.dealerPasswordChange(request);
        }
        
        public string dealerPasswordChange(string parameters) {
            MNepalWeb.NTServices.dealerPasswordChangeRequest inValue = new MNepalWeb.NTServices.dealerPasswordChangeRequest();
            inValue.Body = new MNepalWeb.NTServices.dealerPasswordChangeRequestBody();
            inValue.Body.parameters = parameters;
            MNepalWeb.NTServices.dealerPasswordChangeResponse retVal = ((MNepalWeb.NTServices.NTSoapSoap)(this)).dealerPasswordChange(inValue);
            return retVal.Body.dealerPasswordChangeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MNepalWeb.NTServices.dealerPasswordChangeResponse> MNepalWeb.NTServices.NTSoapSoap.dealerPasswordChangeAsync(MNepalWeb.NTServices.dealerPasswordChangeRequest request) {
            return base.Channel.dealerPasswordChangeAsync(request);
        }
        
        public System.Threading.Tasks.Task<MNepalWeb.NTServices.dealerPasswordChangeResponse> dealerPasswordChangeAsync(string parameters) {
            MNepalWeb.NTServices.dealerPasswordChangeRequest inValue = new MNepalWeb.NTServices.dealerPasswordChangeRequest();
            inValue.Body = new MNepalWeb.NTServices.dealerPasswordChangeRequestBody();
            inValue.Body.parameters = parameters;
            return ((MNepalWeb.NTServices.NTSoapSoap)(this)).dealerPasswordChangeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MNepalWeb.NTServices.getDealerBalanceResponse MNepalWeb.NTServices.NTSoapSoap.getDealerBalance(MNepalWeb.NTServices.getDealerBalanceRequest request) {
            return base.Channel.getDealerBalance(request);
        }
        
        public string getDealerBalance(string mposNumber) {
            MNepalWeb.NTServices.getDealerBalanceRequest inValue = new MNepalWeb.NTServices.getDealerBalanceRequest();
            inValue.Body = new MNepalWeb.NTServices.getDealerBalanceRequestBody();
            inValue.Body.mposNumber = mposNumber;
            MNepalWeb.NTServices.getDealerBalanceResponse retVal = ((MNepalWeb.NTServices.NTSoapSoap)(this)).getDealerBalance(inValue);
            return retVal.Body.getDealerBalanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MNepalWeb.NTServices.getDealerBalanceResponse> MNepalWeb.NTServices.NTSoapSoap.getDealerBalanceAsync(MNepalWeb.NTServices.getDealerBalanceRequest request) {
            return base.Channel.getDealerBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<MNepalWeb.NTServices.getDealerBalanceResponse> getDealerBalanceAsync(string mposNumber) {
            MNepalWeb.NTServices.getDealerBalanceRequest inValue = new MNepalWeb.NTServices.getDealerBalanceRequest();
            inValue.Body = new MNepalWeb.NTServices.getDealerBalanceRequestBody();
            inValue.Body.mposNumber = mposNumber;
            return ((MNepalWeb.NTServices.NTSoapSoap)(this)).getDealerBalanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MNepalWeb.NTServices.eTopupTransferResponse MNepalWeb.NTServices.NTSoapSoap.eTopupTransfer(MNepalWeb.NTServices.eTopupTransferRequest request) {
            return base.Channel.eTopupTransfer(request);
        }
        
        public string eTopupTransfer(string parameters) {
            MNepalWeb.NTServices.eTopupTransferRequest inValue = new MNepalWeb.NTServices.eTopupTransferRequest();
            inValue.Body = new MNepalWeb.NTServices.eTopupTransferRequestBody();
            inValue.Body.parameters = parameters;
            MNepalWeb.NTServices.eTopupTransferResponse retVal = ((MNepalWeb.NTServices.NTSoapSoap)(this)).eTopupTransfer(inValue);
            return retVal.Body.eTopupTransferResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MNepalWeb.NTServices.eTopupTransferResponse> MNepalWeb.NTServices.NTSoapSoap.eTopupTransferAsync(MNepalWeb.NTServices.eTopupTransferRequest request) {
            return base.Channel.eTopupTransferAsync(request);
        }
        
        public System.Threading.Tasks.Task<MNepalWeb.NTServices.eTopupTransferResponse> eTopupTransferAsync(string parameters) {
            MNepalWeb.NTServices.eTopupTransferRequest inValue = new MNepalWeb.NTServices.eTopupTransferRequest();
            inValue.Body = new MNepalWeb.NTServices.eTopupTransferRequestBody();
            inValue.Body.parameters = parameters;
            return ((MNepalWeb.NTServices.NTSoapSoap)(this)).eTopupTransferAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MNepalWeb.NTServices.checkDealerResponse MNepalWeb.NTServices.NTSoapSoap.checkDealer(MNepalWeb.NTServices.checkDealerRequest request) {
            return base.Channel.checkDealer(request);
        }
        
        public string checkDealer(string mposNumber, string Password) {
            MNepalWeb.NTServices.checkDealerRequest inValue = new MNepalWeb.NTServices.checkDealerRequest();
            inValue.Body = new MNepalWeb.NTServices.checkDealerRequestBody();
            inValue.Body.mposNumber = mposNumber;
            inValue.Body.Password = Password;
            MNepalWeb.NTServices.checkDealerResponse retVal = ((MNepalWeb.NTServices.NTSoapSoap)(this)).checkDealer(inValue);
            return retVal.Body.checkDealerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MNepalWeb.NTServices.checkDealerResponse> MNepalWeb.NTServices.NTSoapSoap.checkDealerAsync(MNepalWeb.NTServices.checkDealerRequest request) {
            return base.Channel.checkDealerAsync(request);
        }
        
        public System.Threading.Tasks.Task<MNepalWeb.NTServices.checkDealerResponse> checkDealerAsync(string mposNumber, string Password) {
            MNepalWeb.NTServices.checkDealerRequest inValue = new MNepalWeb.NTServices.checkDealerRequest();
            inValue.Body = new MNepalWeb.NTServices.checkDealerRequestBody();
            inValue.Body.mposNumber = mposNumber;
            inValue.Body.Password = Password;
            return ((MNepalWeb.NTServices.NTSoapSoap)(this)).checkDealerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MNepalWeb.NTServices.checkDealerPasswordResponse MNepalWeb.NTServices.NTSoapSoap.checkDealerPassword(MNepalWeb.NTServices.checkDealerPasswordRequest request) {
            return base.Channel.checkDealerPassword(request);
        }
        
        public string checkDealerPassword(string mposNumber, string Password) {
            MNepalWeb.NTServices.checkDealerPasswordRequest inValue = new MNepalWeb.NTServices.checkDealerPasswordRequest();
            inValue.Body = new MNepalWeb.NTServices.checkDealerPasswordRequestBody();
            inValue.Body.mposNumber = mposNumber;
            inValue.Body.Password = Password;
            MNepalWeb.NTServices.checkDealerPasswordResponse retVal = ((MNepalWeb.NTServices.NTSoapSoap)(this)).checkDealerPassword(inValue);
            return retVal.Body.checkDealerPasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MNepalWeb.NTServices.checkDealerPasswordResponse> MNepalWeb.NTServices.NTSoapSoap.checkDealerPasswordAsync(MNepalWeb.NTServices.checkDealerPasswordRequest request) {
            return base.Channel.checkDealerPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<MNepalWeb.NTServices.checkDealerPasswordResponse> checkDealerPasswordAsync(string mposNumber, string Password) {
            MNepalWeb.NTServices.checkDealerPasswordRequest inValue = new MNepalWeb.NTServices.checkDealerPasswordRequest();
            inValue.Body = new MNepalWeb.NTServices.checkDealerPasswordRequestBody();
            inValue.Body.mposNumber = mposNumber;
            inValue.Body.Password = Password;
            return ((MNepalWeb.NTServices.NTSoapSoap)(this)).checkDealerPasswordAsync(inValue);
        }
    }
}
