//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.MNepal.MerchantReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.nibl.com.np/", ConfigurationName="MerchantReference.CommonInterfaceSoap")]
    public interface CommonInterfaceSoap {
        
        // CODEGEN: Generating message contract since message SubmitRequestRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nibl.com.np/SubmitRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WCF.MNepal.MerchantReference.SubmitRequestResponse SubmitRequest(WCF.MNepal.MerchantReference.SubmitRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nibl.com.np/SubmitRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<WCF.MNepal.MerchantReference.SubmitRequestResponse> SubmitRequestAsync(WCF.MNepal.MerchantReference.SubmitRequestRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nibl.com.np/")]
    public partial class HeaderInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string h1Field;
        
        private string h2Field;
        
        private string h3Field;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string H1 {
            get {
                return this.h1Field;
            }
            set {
                this.h1Field = value;
                this.RaisePropertyChanged("H1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string H2 {
            get {
                return this.h2Field;
            }
            set {
                this.h2Field = value;
                this.RaisePropertyChanged("H2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string H3 {
            get {
                return this.h3Field;
            }
            set {
                this.h3Field = value;
                this.RaisePropertyChanged("H3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nibl.com.np/")]
    public partial class ResponseData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultCodeField;
        
        private string resultDescriptionField;
        
        private string additionalDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ResultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
                this.RaisePropertyChanged("ResultCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ResultDescription {
            get {
                return this.resultDescriptionField;
            }
            set {
                this.resultDescriptionField = value;
                this.RaisePropertyChanged("ResultDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AdditionalData {
            get {
                return this.additionalDataField;
            }
            set {
                this.additionalDataField = value;
                this.RaisePropertyChanged("AdditionalData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nibl.com.np/")]
    public partial class RequestData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object field1Field;
        
        private object field2Field;
        
        private object field3Field;
        
        private object field4Field;
        
        private object field5Field;
        
        private object field6Field;
        
        private object field7Field;
        
        private object field8Field;
        
        private object field9Field;
        
        private object field10Field;
        
        private object field11Field;
        
        private object field12Field;
        
        private object field13Field;
        
        private object field14Field;
        
        private object field15Field;
        
        private object field16Field;
        
        private object field17Field;
        
        private object field18Field;
        
        private object field19Field;
        
        private object field20Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public object Field1 {
            get {
                return this.field1Field;
            }
            set {
                this.field1Field = value;
                this.RaisePropertyChanged("Field1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public object Field2 {
            get {
                return this.field2Field;
            }
            set {
                this.field2Field = value;
                this.RaisePropertyChanged("Field2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public object Field3 {
            get {
                return this.field3Field;
            }
            set {
                this.field3Field = value;
                this.RaisePropertyChanged("Field3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public object Field4 {
            get {
                return this.field4Field;
            }
            set {
                this.field4Field = value;
                this.RaisePropertyChanged("Field4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public object Field5 {
            get {
                return this.field5Field;
            }
            set {
                this.field5Field = value;
                this.RaisePropertyChanged("Field5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public object Field6 {
            get {
                return this.field6Field;
            }
            set {
                this.field6Field = value;
                this.RaisePropertyChanged("Field6");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public object Field7 {
            get {
                return this.field7Field;
            }
            set {
                this.field7Field = value;
                this.RaisePropertyChanged("Field7");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public object Field8 {
            get {
                return this.field8Field;
            }
            set {
                this.field8Field = value;
                this.RaisePropertyChanged("Field8");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public object Field9 {
            get {
                return this.field9Field;
            }
            set {
                this.field9Field = value;
                this.RaisePropertyChanged("Field9");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public object Field10 {
            get {
                return this.field10Field;
            }
            set {
                this.field10Field = value;
                this.RaisePropertyChanged("Field10");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public object Field11 {
            get {
                return this.field11Field;
            }
            set {
                this.field11Field = value;
                this.RaisePropertyChanged("Field11");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public object Field12 {
            get {
                return this.field12Field;
            }
            set {
                this.field12Field = value;
                this.RaisePropertyChanged("Field12");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public object Field13 {
            get {
                return this.field13Field;
            }
            set {
                this.field13Field = value;
                this.RaisePropertyChanged("Field13");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public object Field14 {
            get {
                return this.field14Field;
            }
            set {
                this.field14Field = value;
                this.RaisePropertyChanged("Field14");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public object Field15 {
            get {
                return this.field15Field;
            }
            set {
                this.field15Field = value;
                this.RaisePropertyChanged("Field15");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public object Field16 {
            get {
                return this.field16Field;
            }
            set {
                this.field16Field = value;
                this.RaisePropertyChanged("Field16");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public object Field17 {
            get {
                return this.field17Field;
            }
            set {
                this.field17Field = value;
                this.RaisePropertyChanged("Field17");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public object Field18 {
            get {
                return this.field18Field;
            }
            set {
                this.field18Field = value;
                this.RaisePropertyChanged("Field18");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public object Field19 {
            get {
                return this.field19Field;
            }
            set {
                this.field19Field = value;
                this.RaisePropertyChanged("Field19");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public object Field20 {
            get {
                return this.field20Field;
            }
            set {
                this.field20Field = value;
                this.RaisePropertyChanged("Field20");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubmitRequest", WrapperNamespace="http://www.nibl.com.np/", IsWrapped=true)]
    public partial class SubmitRequestRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.nibl.com.np/")]
        public WCF.MNepal.MerchantReference.HeaderInfo HeaderInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.nibl.com.np/", Order=0)]
        public string serviceId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.nibl.com.np/", Order=1)]
        public string serviceCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.nibl.com.np/", Order=2)]
        public WCF.MNepal.MerchantReference.RequestData input;
        
        public SubmitRequestRequest() {
        }
        
        public SubmitRequestRequest(WCF.MNepal.MerchantReference.HeaderInfo HeaderInfo, string serviceId, string serviceCode, WCF.MNepal.MerchantReference.RequestData input) {
            this.HeaderInfo = HeaderInfo;
            this.serviceId = serviceId;
            this.serviceCode = serviceCode;
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubmitRequestResponse", WrapperNamespace="http://www.nibl.com.np/", IsWrapped=true)]
    public partial class SubmitRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.nibl.com.np/", Order=0)]
        public WCF.MNepal.MerchantReference.ResponseData SubmitRequestResult;
        
        public SubmitRequestResponse() {
        }
        
        public SubmitRequestResponse(WCF.MNepal.MerchantReference.ResponseData SubmitRequestResult) {
            this.SubmitRequestResult = SubmitRequestResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CommonInterfaceSoapChannel : WCF.MNepal.MerchantReference.CommonInterfaceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommonInterfaceSoapClient : System.ServiceModel.ClientBase<WCF.MNepal.MerchantReference.CommonInterfaceSoap>, WCF.MNepal.MerchantReference.CommonInterfaceSoap {
        
        public CommonInterfaceSoapClient() {
        }
        
        public CommonInterfaceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CommonInterfaceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommonInterfaceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommonInterfaceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCF.MNepal.MerchantReference.SubmitRequestResponse WCF.MNepal.MerchantReference.CommonInterfaceSoap.SubmitRequest(WCF.MNepal.MerchantReference.SubmitRequestRequest request) {
            return base.Channel.SubmitRequest(request);
        }
        
        public WCF.MNepal.MerchantReference.ResponseData SubmitRequest(WCF.MNepal.MerchantReference.HeaderInfo HeaderInfo, string serviceId, string serviceCode, WCF.MNepal.MerchantReference.RequestData input) {
            WCF.MNepal.MerchantReference.SubmitRequestRequest inValue = new WCF.MNepal.MerchantReference.SubmitRequestRequest();
            inValue.HeaderInfo = HeaderInfo;
            inValue.serviceId = serviceId;
            inValue.serviceCode = serviceCode;
            inValue.input = input;
            WCF.MNepal.MerchantReference.SubmitRequestResponse retVal = ((WCF.MNepal.MerchantReference.CommonInterfaceSoap)(this)).SubmitRequest(inValue);
            return retVal.SubmitRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WCF.MNepal.MerchantReference.SubmitRequestResponse> WCF.MNepal.MerchantReference.CommonInterfaceSoap.SubmitRequestAsync(WCF.MNepal.MerchantReference.SubmitRequestRequest request) {
            return base.Channel.SubmitRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCF.MNepal.MerchantReference.SubmitRequestResponse> SubmitRequestAsync(WCF.MNepal.MerchantReference.HeaderInfo HeaderInfo, string serviceId, string serviceCode, WCF.MNepal.MerchantReference.RequestData input) {
            WCF.MNepal.MerchantReference.SubmitRequestRequest inValue = new WCF.MNepal.MerchantReference.SubmitRequestRequest();
            inValue.HeaderInfo = HeaderInfo;
            inValue.serviceId = serviceId;
            inValue.serviceCode = serviceCode;
            inValue.input = input;
            return ((WCF.MNepal.MerchantReference.CommonInterfaceSoap)(this)).SubmitRequestAsync(inValue);
        }
    }
}
